apiVersion: apps/v1
kind: Deployment
metadata:
  name: bello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bello-app
  template:
    metadata:
      labels:
        app: bello-app
    spec:
      containers:
      - name: bello-app
        image: bello-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bello-app-configmap
              key: database_url
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bello-mysql-pass
              key: password
        - name: DB_USER
          value: root
        - name: DB_NAME
          value: bello_auth
        - name: DB_DIALECT
          value: mysql
        - name: DB_PORT
          value: '3306'
        - name: PORT
          value: '8000'
        - name: HOST
          value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
  name: bello-app-loadbalancer
spec:
  selector:
    app: bello-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
