USE bello_auth;

CREATE TABLE user (
  id BINARY(36) PRIMARY KEY,
  email NVARCHAR(50) NOT NULL,
  password_token NVARCHAR(321) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL
)