// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Bello app auth
An API for bello app authentication


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
