// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for bello app authentication",
    "title": "Bello app auth",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/status": {
      "get": {
        "description": "Used for checking service status and code hash",
        "tags": [
          "Status"
        ],
        "operationId": "serviceStatus",
        "responses": {
          "200": {
            "description": "Status response",
            "schema": {
              "$ref": "#/definitions/StatusResponse"
            }
          },
          "500": {
            "description": "Service down",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "enum": [
            "InternalServerError",
            "Unauthorized",
            "NotFound",
            "BadRequest"
          ]
        },
        "type": {
          "type": "string"
        }
      }
    },
    "StatusResponse": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Status endpoints",
      "name": "Status"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for bello app authentication",
    "title": "Bello app auth",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/status": {
      "get": {
        "description": "Used for checking service status and code hash",
        "tags": [
          "Status"
        ],
        "operationId": "serviceStatus",
        "responses": {
          "200": {
            "description": "Status response",
            "schema": {
              "$ref": "#/definitions/StatusResponse"
            }
          },
          "500": {
            "description": "Service down",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "enum": [
            "InternalServerError",
            "Unauthorized",
            "NotFound",
            "BadRequest"
          ]
        },
        "type": {
          "type": "string"
        }
      }
    },
    "StatusResponse": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Status endpoints",
      "name": "Status"
    }
  ]
}`))
}
