// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RefreshAccessTokenHandlerFunc turns a function with the right signature into a refresh access token handler
type RefreshAccessTokenHandlerFunc func(RefreshAccessTokenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RefreshAccessTokenHandlerFunc) Handle(params RefreshAccessTokenParams) middleware.Responder {
	return fn(params)
}

// RefreshAccessTokenHandler interface for that can handle valid refresh access token params
type RefreshAccessTokenHandler interface {
	Handle(RefreshAccessTokenParams) middleware.Responder
}

// NewRefreshAccessToken creates a new http.Handler for the refresh access token operation
func NewRefreshAccessToken(ctx *middleware.Context, handler RefreshAccessTokenHandler) *RefreshAccessToken {
	return &RefreshAccessToken{Context: ctx, Handler: handler}
}

/*RefreshAccessToken swagger:route POST /v1/user/refresh User refreshAccessToken

Refresh access token

*/
type RefreshAccessToken struct {
	Context *middleware.Context
	Handler RefreshAccessTokenHandler
}

func (o *RefreshAccessToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRefreshAccessTokenParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
