// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	apimodel "github.com/adasiunas/bello-auth/apimodel"
)

// NewRefreshAccessTokenParams creates a new RefreshAccessTokenParams object
// no default values defined in spec.
func NewRefreshAccessTokenParams() RefreshAccessTokenParams {

	return RefreshAccessTokenParams{}
}

// RefreshAccessTokenParams contains all the bound params for the refresh access token operation
// typically these are obtained from a http.Request
//
// swagger:parameters refreshAccessToken
type RefreshAccessTokenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Token *apimodel.RefreshRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRefreshAccessTokenParams() beforehand.
func (o *RefreshAccessTokenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body apimodel.RefreshRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("token", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Token = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
